### PR TITLE
chore: sync develop branch

### PR DESCRIPTION
**Pull request by HarunamiYaki**
## Changes
update `develop` branch to keep this branch up-to-date with `v5` branch

## Status

- [x] Follow the installation from <a href="https://github.com/Muunatic/RyU#how-to-use">**README**</a>.
- [x] Add or edit tests to reflect the change.
- [x] Run npm test.

### CODE REVIEW

**Comment by HarunamiYaki** [comment]
PRs passed the test and doesn't make a merge conflict, you can approve these PRs @Muunatic

**Comment by Muunatic** [comment]
> PRs passed the test and doesn't make a merge conflict, you can approve these PRs @Muunatic

dang, LGTM thanks for the patch I'll approve these PRs

**Review by Muunatic — APPROVED** [review]
LGTM!

**Comment by HarunamiYaki** [comment]
Ready to merge

**Pull request merged**
